### ISSUE TITLE
Messages from the DBErrors.log

### ISSUE THREAD

**Issue by pangolp** [gpn39f/ArkCORE-434#3]
**SMALL DESCRIPTION:**
List of messages that appear in the log. The idea is to generate the list and to run them little by little.

- [ ] Creature (Entry: 36839) has `difficulty_entry_2`=3683902 but creature entry 3683902 does not exist.
- [ ] Spell (ID: 82175) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc and not 100% chance random discovery ability but listed for spellId 82180 (and maybe more) in `skill_discovery_template` table
- [ ] Spell (ID: 81275) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc and not 100% chance random discovery ability but listed for spellId 82180 (and maybe more) in `skill_discovery_template` table
- [ ] Script named 'spell_dk_advantage_t10_4p' does not have a script name assigned in database.
- [ ] Script named 'spell_dk_dancing_rune_weapon' does not have a script name assigned in database.
- [ ] Script named 'spell_dk_pvp_4p_bonus' does not have a script name assigned in database.
- [ ] Script named 'spell_dru_forms_trinket' does not have a script name assigned in database.
- [ ] Script named 'spell_dru_flight_form' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_blood_reserve' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_burning_depths_necrolyte_image' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_gm_freeze' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_stand' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_landmine_knockback_achievement' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_clear_debuffs' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_mark_of_kazrogal_hellfire' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_face_rage' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_magic_rooster' does not have a script name assigned in database.
- [ ] Script named 'spell_hun_improved_steady_shot' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_orb_filter' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_pyromaniac' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_frostfire_bolt' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_icy_veins' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_piercing_chill' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_combustion' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_impact' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_ritual_of_refreshment' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_pet_scaling_05' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_mirror_image' does not have a script name assigned in database.
- [ ] Script named 'spell_mage_deep_freeze' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_item_t6_trinket' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_light_s_beacon' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_t3_6p_bonus' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_t8_2p_bonus' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_seal_of_insight' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_consecration' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_consecration_damage' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_ligh_of_dawn' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_avenger_shield' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_flash_of_light' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_inquisition' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_guardian_of_ancient_kings_retri' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_guardian_of_ancient_kings' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_ancient_fury' does not have a script name assigned in database.
- [ ] Script named 'spell_pal_judgement_damage' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_cure_disease' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_mind_sear_spell' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_mind_blast' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_mind_spike' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_fade' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_inner_fire' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_shadow_orbs' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_inner_focus' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_atonement_heal' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_power_word_barrier' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_holyword_sanctuary_heal' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_fear' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_friendly_dispel' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_spirit_of_redemption_form' does not have a script name assigned in database.
- [ ] Script named 'spell_pri_spirit_of_redemption' does not have a script name assigned in database.
- [ ] Script named 'spell_warl_soulfire' does not have a script name assigned in database.
- [ ] Script named 'spell_warl_rain_of_fire' does not have a script name assigned in database.
- [ ] Script named 'spell_item_fate_rune_of_unsurpassed_vigor' does not have a script name assigned in database.
- [ ] Script named 'spell_item_flask_of_enhancement' does not have a script name assigned in database.
- [ ] Script named 'spell_item_grounded_plasma_shield' does not have a script name assigned in database.
- [ ] Script named 'spell_hallow_end_candy' does not have a script name assigned in database.
- [ ] Script named 'spell_hallow_end_candy_pirate' does not have a script name assigned in database.
- [ ] Script named 'spell_hallow_end_wand' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_feast_on' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_well_fed_turkey' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_well_fed_cranberry' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_well_fed_stuffing' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_well_fed_sweet_potatoes' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_well_fed_pie' does not have a script name assigned in database.
- [ ] Script named 'spell_pilgrims_bounty_turkey_tracker' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_giddyup' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_ram' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_ram_fatigue' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_apple_trap' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_exhausted_ram' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_relay_race_intro_force_player_to_throw' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_dismount_ram' does not have a script name assigned in database.
- [ ] Script named 'spell_brewfest_barker_bunny' does not have a script name assigned in database.
- [ ] Script named 'spell_gen_ribbon_pole_dancer_check' does not have a script name assigned in database.
- [ ] Script named 'spell_swipe_honey_88254' does not have a script name assigned in database.
- [ ] Script named 'go_totem_of_ruumbo_206585' does not have a script name assigned in database.
- [ ] Script named 'npc_ferli_47558' does not have a script name assigned in database.
- [ ] Script named 'npc_wandering_forest_walker_7584' does not have a script name assigned in database.

**OPERATING SYSTEM:**
Debian 10

**Comment by CrossUCI** [comment]
You need to import all the sql from the folder sql/updates/world

**Comment by pangolp** [comment]
Does that fix it? @CrossUCI

**Comment by CrossUCI** [comment]
Allmost all, except for
Script named 'spell_swipe_honey_88254' does not have a script name assigned in database.
Script named 'go_totem_of_ruumbo_206585' does not have a script name assigned in database.
Script named 'npc_ferli_47558' does not have a script name assigned in database.
Script named 'npc_wandering_forest_walker_7584' does not have a script name assigned in database.

**Comment by pangolp** [comment]
Good, then we have to work on accommodating the SQL folder. In another repository, I'm saying base, custom and updates. Then I would have to do something similar to that here. You can see that I'm telling you here: https://github.com/pangolp/cataclysm434/tree/master/sql even though I haven't finished the world table yet. In the env folder, I have a small .sh that transforms all the .sql into 1. https://github.com/pangolp/cataclysm434/tree/master/env. Later on in env, the idea is to have a basic one, a custom one and an update one.

**Comment by pangolp** [comment]
I close it then to the subject, since in the end it was a problem of updates.
